name: Automatic Data Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  DataUpdater:
    name: Automatic Data Update
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ItzDerock'
    steps:
      - name: Checkout Project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Use Node.js v18
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: './package-lock.json'
      - name: Install Dependencies
        run: npm install
      - name: Run updater
        run: node --experimental-json-modules scripts/twemoji-regex-updater.mjs
      - name: Run prettier on the code
        run: npm run format
      - name: Commit any changes and create a pull request
        env:
          GITHUB_USER: github-actions[bot]
          GITHUB_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .;
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit, exiting with code 0"
            exit 0;
          else
            git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git";
            git config --local user.email "${GITHUB_EMAIL}";
            git config --local user.name "${GITHUB_USER}";
            git checkout -b update-twemoji-regex/$(date +%F-%H-%M);
            git commit -sam "feat: update Twemoji Regex";
            git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)
            gh pr create -t "feat: update twemoji regex" -b "*bleep bloop* I updated the Twemoji Regex" -B main;
          fi
