import 'react';
import type * as Components from '@skyra/discord-components-core';

type LitElementProps<T> = React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> &
  Omit<
    {
      // eslint-disable-next-line @typescript-eslint/no-unsafe-function-type
      [K in keyof T]?: T[K] extends Function ? never : T[K] extends object ? string | undefined : T[K] | undefined;
    },
    'children' | 'style' | 'className'
  >;

/*
  Autogenerated with
  ```
    # Finds all exported class names and generates the mapping lines
    grep -r "export class Discord" packages/core/src/components | \
    awk -F 'class ' '{print $2}' | awk '{print $1}' | \
    while read class; do
      # convert CamelCase to kebab-case
      tag=$(echo "$class" | sed -r 's/([a-z0-9])([A-Z])/\1-\2/g' | tr '[:upper:]' '[:lower:]')
      echo "'$tag': LitElementProps<Components.$class>;"
    done
  ```
  inside of @skyra/discord-components
*/

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      'discord-subscript': LitElementProps<Components.DiscordSubscript>;
      'discord-embed-footer': LitElementProps<Components.DiscordEmbedFooter>;
      'discord-mention': LitElementProps<Components.DiscordMention>;
      'discord-list-item': LitElementProps<Components.DiscordListItem>;
      'discord-embed-description': LitElementProps<Components.DiscordEmbedDescription>;
      'discord-messages': LitElementProps<Components.DiscordMessages>;
      'discord-embed-fields': LitElementProps<Components.DiscordEmbedFields>;
      'discord-button': LitElementProps<Components.DiscordButton>;
      'discord-embed': LitElementProps<Components.DiscordEmbed>;
      'discord-italic': LitElementProps<Components.DiscordItalic>;
      'discord-invite': LitElementProps<Components.DiscordInvite>;
      'discord-file-attachment': LitElementProps<Components.DiscordFileAttachment>;
      'discord-unordered-list': LitElementProps<Components.DiscordUnorderedList>;
      'discord-modal': LitElementProps<Components.DiscordModal>;
      'discord-message': LitElementProps<Components.DiscordMessage>;
      'discord-thread-message': LitElementProps<Components.DiscordThreadMessage>;
      'discord-tenor-video': LitElementProps<Components.DiscordTenorVideo>;
      'discord-custom-emoji': LitElementProps<Components.DiscordCustomEmoji>;
      'discord-poll': LitElementProps<Components.DiscordPoll>;
      'discord-string-select-menu': LitElementProps<Components.DiscordStringSelectMenu>;
      'discord-author-info': LitElementProps<Components.DiscordAuthorInfo>;
      'discord-command': LitElementProps<Components.DiscordCommand>;
      'discord-reply': LitElementProps<Components.DiscordReply>;
      'discord-embed-field': LitElementProps<Components.DiscordEmbedField>;
      'discord-code': LitElementProps<Components.DiscordCode>;
      'discord-link': LitElementProps<Components.DiscordLink>;
      'discord-action-row': LitElementProps<Components.DiscordActionRow>;
      'discord-pre': LitElementProps<Components.DiscordPre>;
      'discord-poll-answer': LitElementProps<Components.DiscordPollAnswer>;
      'discord-bold': LitElementProps<Components.DiscordBold>;
      'discord-reaction': LitElementProps<Components.DiscordReaction>;
      'discord-media-lifecycle': LitElementProps<Components.DiscordMediaLifecycle>;
      'discord-image-attachment': LitElementProps<Components.DiscordImageAttachment>;
      'discord-thread': LitElementProps<Components.DiscordThread>;
      'discord-quote': LitElementProps<Components.DiscordQuote>;
      'discord-string-select-menu-option': LitElementProps<Components.DiscordStringSelectMenuOption>;
      'discord-verified-author-tag': LitElementProps<Components.DiscordVerifiedAuthorTag>;
      'discord-attachments': LitElementProps<Components.DiscordAttachments>;
      'discord-reactions': LitElementProps<Components.DiscordReactions>;
      'discord-input-text': LitElementProps<Components.DiscordInputText>;
      'discord-system-message': LitElementProps<Components.DiscordSystemMessage>;
      'discord-video-attachment': LitElementProps<Components.DiscordVideoAttachment>;
      'discord-ordered-list': LitElementProps<Components.DiscordOrderedList>;
      'discord-spoiler': LitElementProps<Components.DiscordSpoiler>;
      'discord-time': LitElementProps<Components.DiscordTime>;
      'discord-header': LitElementProps<Components.DiscordHeader>;
      'discord-underlined': LitElementProps<Components.DiscordUnderlined>;
      'discord-audio-attachment': LitElementProps<Components.DiscordAudioAttachment>;
    }
  }
}
