const defaultPFP = 'https://cdn.discordapp.com/embed/avatars/0.png';

const DummyUser = {
    bot: false,
    id: '00000000000',
    tag: "Unknown User#0000",
    name: "Unknown User",
    username: "Unknown User",
    hexAccentColor: "#FFFFFF",
    avatarURL: () => 'https://cdn.discordapp.com/embed/avatars/0.png'
};

const LanguageAliases = {
    'ts': 'typescript',
    'js': 'javascript',
    'py': 'python',
    'rb': 'ruby',
};

export { defaultPFP, DummyUser, LanguageAliases };

// for use with xss module
// module.exports.xssSettings = {
//     a: [],
//     abbr: [],
//     address: [],
//     area: [],
//     article: [],
//     aside: [],
//     audio: [],
//     b: [],
//     bdi: [],
//     bdo: [],
//     big: [],
//     blockquote: [],
//     br: [],
//     caption: [],
//     center: [],
//     cite: [],
//     code: [],
//     col: [],
//     colgroup: [],
//     dd: [],
//     del: [],
//     details: [],
//     div: [],
//     dl: [],
//     dt: [],
//     em: [],
//     figcaption: [],
//     figure: [],
//     font: [],
//     footer: [],
//     h1: [],
//     h2: [],
//     h3: [],
//     h4: [],
//     h5: [],
//     h6: [],
//     header: [],
//     hr: [],
//     i: [],
//     img: [],
//     ins: [],
//     li: [],
//     mark: [],
//     nav: [],
//     ol: [],
//     p: [],
//     pre: [],
//     s: [],
//     section: [],
//     small: [],
//     span: [],
//     sub: [],
//     summary: [],
//     sup: [],
//     strong: [],
//     strike: [],
//     table: [],
//     tbody: [],
//     td: [],
//     tfoot: [],
//     th: [],
//     thead: [],
//     tr: [],
//     tt: [],
//     u: [],
//     ul: [],
//     video: [],
// }